#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

  env_must_be="developer/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

set -e
set -x


cd "$REPO_HOME"/developer || exit 1

# remove object files, deps file, library, and whatever else is on the scratchpad if anything
  rm scratchpad/*.o $DEPFILE scratchpad/lib*.a   || true

# remove built executables
  rm -f machine/* || true

set +x
echo "$(script_fn) done."
