#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# before running this, make library is built and is in the scratchpad directory

# input guards

  env_must_be="developer/tool/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

set -e
set -x

  cd "$REPO_HOME"/developer || exit 1

  release_dir=$(release_dir)

  if [ ! -d ${release_dir} ]; then
    echo "$(script_fp):: no release directory: " ${release_dir}
    exit 1
  fi

  rm_na -rf ${release_dir}/*

set +x
echo "$(script_fn) done."

