#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# This is a bespoke script for copying files into ../release.
# Files in ../release can be used by the tester role.
# On a release branch, files in the ../release constitute the public release.

# conventional preliminaries

  env_must_be="developer/tool/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

  cd "$REPO_HOME"/developer || exit 1

#set -e
#set -x

cd "$REPO_HOME/developer"

release_dir="$REPO_HOME/release"
ko_dir="scratchpad/kmod"
machine_executable_list="scratchpad/hello"

# Enable nullglob so an empty match yields an empty list (not the literal pattern)
shopt -s nullglob

# zero or more machine executables
for fglob in $machine_executable_list; do
  # nesting the loop allows that $fglob is a file glob, and expands it
  for f in $fglob; do
    if [[ -x "$f" ]]; then
      echo "+ install -m 0500 '$f' '$release_dir/machine/'"
      install -m 0550 "$f" "$release_dir/machine/"
    else
      echo "(info) did not find '$f'"
    fi
  done
done

# zero or more Kernel modules
# release/kmod created 750 so developer can write to it, group can read it
ko_list=("$ko_dir"/*.ko)
if (( ${#ko_list[@]} )); then
  if [[ ! -d "$release_dir/kmod" ]]; then
    echo "+ install -d '$release_dir/kmod'"
    install -m 750 -d "$release_dir/kmod"
  fi
  for f in "${ko_list[@]}"; do
    echo "+ install -m 0440 '$f' '$release_dir/kmod/'"
    install -m 440 "$f" "$release_dir/kmod/"
  done
else
  echo "(info) no kmod artifacts found in $ko_dir; skipping kmod release"
fi

echo "$script_fn done."
