#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# This is a bespoke script for copying files into ../release.
# Files in ../release can be used by the tester role.
# On a release branch, files in the ../release constitute the public release.

# conventional preliminaries

  env_must_be="developer/tool/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

  cd "$REPO_HOME"/developer || exit 1

#set -e
#set -x

release_dir="$REPO_HOME/release"

mkdir -p ${release_dir}/kmod && install -m 0600 scratchpad/*.ko   "${release_dir}/kmod/"
install -m 0700 scratchpad/hello  "${release_dir}/machine/"

echo "$(script_fn) done."

