* Project Workflow


This document outlines the responsibilities of different roles in the project and the release process.

** 1. Project Administrator
   - Download the project from GitHub.
   - Install the required tools.
   - Explain workflows and file locations to project members.
   - Manage Major and Minor Releases.

** 2. Developer
   - From the `Harmony/` directory, run:
     #+begin_src sh
       source env_developer
     #+end_src
     to set up the developer environment.
   - Build the project:
     #+begin_src sh
       make
     #+end_src
   - Copy relevant files to the release directory:
     #+begin_src sh
       release
     #+end_src
   - The tester will evaluate the release candidate.

** 3. Tester
   - From the `Harmony/` directory, set up the testing environment:
     #+begin_src sh
       source env_tester
     #+end_src
   - Build and run tests:
     #+begin_src sh
       make
       shell/test_<name>
     #+end_src
   - Alternatively, change to a test directory, source its environment, and run tests manually.
   - The development and testing process will iterate until the release candidate is ready for an official release.

** 4. Major Release
   - The release candidate is in `$REPO_HOME/release` and has passed testing.
   - Verify that `$REPO_HOME/tool_shared/bespoke/version` outputs the correct version information. Modify it if necessary.
   - Create a new branch named `release_v<n>.0` where `<n>` is the major version.
   - Rename the release directory to `$REPO_HOME/release_v<n>.0` and create a new empty `$REPO_HOME/release/` directory.

** 5. Minor Release
   - Urgent changes to a major release are made on its corresponding branch.
   - The developer makes edits, and the tester evaluates the release candidate as usual.
   - The `version` program is updated.
   - Rename the release directory to `release_v<n>.<m>`, where `<m>` is the minor version.
   - Merge changes into `core_developer_branch` if necessary.

** 6. Tips
   - If acting in multiple roles (developer, tester, admin), keep separate terminal shells for each role to avoid misconfigurations.
